package eu.delving.domain;

import java.util.EnumSet;
import java.util.Set;

/**
 * All of the languages supported
 *
 * @author Gerald de Jong, Beautiful Code BV, <geralddejong@gmail.com>
 * @author Nicola Aloia <nicola.aloia@isti.cnr.it>
 *
 */

public enum Language {

    AB("Abkhazian", "abk"),
    ACE("Achinese"),
    ACH("Acoli"),
    ADA("Adangme"),
    ADY("Adyghe; Adygei"),
    AE("Avestan", "ave"),
    AF("Afrikaans", "afr"),
    AFA("Afro-Asiatic (Other),"),
    AFH("Afrihili"),
    AK("Akan", "aka"),
    AKK("Akkadian"),
    ALE("Aleut"),
    ALG("Algonquian languages"),
    ALT("Southern Altai"),
    AM("Amharic", "amh"),
    AN("Aragonese"),
    ANG("English, Old (ca.450-1100),"),
    APA("Apache languages"),
    AR("Arabic", "ara"),
    ARC("Aramaic"),
    ARG("Aragonese"),
    ARN("Araucanian"),
    ARP("Arapaho"),
    ART("Artificial (Other),"),
    ARW("Arawak"),
    AS("Assamese", "asm"),
    AST("Asturian; Bable"),
    ATH("Athapascan languages"),
    AUS("Australian languages"),
    AV("Avaric", "ava"),
    AWA("Awadhi"),
    AY("Aymara", "aym"),
    AZ("Azerbaijani", "aze"),
    BA("Bashkir", "bak"),
    BAD("Banda"),
    BAI("Bamileke languages"),
    BAL("Baluchi"),
    BAM("Bambara"),
    BAN("Balinese"),
    BAS("Basa"),
    BAT("Baltic (Other),"),
    BE("Belarusian", "bel"),
    BEJ("Beja"),
    BEM("Bemba"),
    BN("Bengali", "ben"),
    BER("Berber (Other),"),
    BG(false, true, "Bulgarian", "bul"),
    BH("Bihari"),
    BHO("Bhojpuri"),
    BI("Bislama"),
    BIH("Bihari"),
    BIK("Bikol"),
    BIN("Bini"),
    BIS("Bislama"),
    BLA("Siksika"),
    BM("Bambara"),
    BNT("Bantu (Other),"),
    BO("Tibetan", "bod"),
    BR("Breton", "bre"),
    BRA("Braj"),
    BS("Bosnian", "bos"),
    BTK("Batak (Indonesia),"),
    BUA("Buriat"),
    BUG("Buginese"),
    BYN("Blin; Bilin"),
    CA(false, true, "Catalan; Valencian", "cat", "catalan"),
    CAD("Caddo"),
    CAI("Central American Indian (Other),"),
    CAR("Carib"),
    CAU("Caucasian (Other),"),
    CE("Chechen", "che"),
    CEB("Cebuano"),
    CEL("Celtic (Other),"),
    CH("Chamorro"),
    CHA("Chamorro"),
    CHB("Chibcha"),
    CHG("Chagatai"),
    CHK("Chuukese"),
    CHM("Mari"),
    CHN("Chinook jargon"),
    CHO("Choctaw"),
    CHP("Chipewyan"),
    CHR("Cherokee"),
    CHU("Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
    CHV("Chuvash"),
    CHY("Cheyenne"),
    CMC("Chamic languages"),
    CO("Corsican"),
    COP("Coptic"),
    COR("Cornish"),
    COS("Corsican"),
    CPE("Creoles and pidgins, English based (Other),"),
    CPF("Creoles and pidgins, French-based (Other),"),
    CPP("Creoles and pidgins, Portuguese-based (Other),"),
    CR("Cree", "cre"),
    CRH("Crimean Tatar; Crimean Turkish"),
    CRP("Creoles and pidgins (Other),"),
    CS(false, true, "Czech", "cze", "ces"),
    CSB("Kashubian"),
    CU("Old Bulgarian; Old Slavonic; Church Slavonic; Church Slavic; Old Church Slavonic"),
    CUS("Cushitic (Other),"),
    CV("Chuvash"),
    CY("Welsh", "cym"),
    DA(false, true, "Danish", "dan", "danish"),
    DAK("Dakota"),
    DAR("Dargwa"),
    DAY("Dayak"),
    DE(true, true, "German", "deu", "ger", "german"),
    DEL("Delaware"),
    DEN("Slave (Athapascan),"),
    DGR("Dogrib"),
    DIN("Dinka"),
    DIV("Divehi"),
    DOI("Dogri"),
    DRA("Dravidian (Other),"),
    DSB("Lower Sorbian"),
    DUA("Duala"),
    DUM("Dutch, Middle (ca.1050-1350),"),
    DV("Divehi"),
    DYU("Dyula"),
    DZ("Dzongkha"),
    DZO("Dzongkha"),
    EE("Ewe"),
    EFI("Efik"),
    EGY("Egyptian (Ancient),"),
    EKA("Ekajuk"),
    EL(false, true, "Greek, Modern (1453-)", "ell", "gre", "greac?", "greaca", "greek"),
    ELX("Elamite"),
    EN(true, true, "English", "eng", "uk", "us", "englez?", "english"),
    ENM("English, Middle (1100-1500),"),
    EO("Esperanto", "epo"),
    ES(true, true, "Castilian; Spanish", "spa", "spanish"),
    ET(false, true, "Estonian", "est"),
    EU("Basque", "eus"),
    EWE("Ewe"),
    EWO("Ewondo"),
    FA("Persian", "fas"),
    FAN("Fang"),
    FAO("Faroese"),
    FAS("Persian"),
    FAT("Fanti"),
    FF("Fulah"),
    FI(false, true, "Finnish", "fin", "finnish"),
    FIJ("Fijian"),
    FIL("Filipino; Pilipino"),
    FIU("Finno-Ugrian (Other),"),
    FJ("Fijian"),
    FO("Faroese"),
    FON("Fon"),
    FR(true, true, "French", "fre", "fra", "french", "fro", "frm"),
    FUL("Fulah"),
    FUR("Friulian"),
    FY("Frisian", "fry"),
    GA(false, true, "Irish", "gle"),
    GAA("Ga"),
    GAY("Gayo"),
    GBA("Gbaya"),
    GD("Scottish Gaelic; Gaelic"),
    GEM("Germanic (Other),"),
    GEZ("Geez"),
    GIL("Gilbertese"),
    GL("Gallegan"),
    GLA("Gaelic; Scottish Gaelic"),
    GLG("Gallegan"),
    GLV("Manx"),
    GMH("German, Middle High (ca.1050-1500),"),
    GN("Guarani"),
    GOH("German, Old High (ca.750-1050),"),
    GON("Gondi"),
    GOR("Gorontalo"),
    GOT("Gothic"),
    GRB("Grebo"),
    GRC("Greek, Ancient (to 1453),"),
    GRN("Guarani"),
    GU("Gujarati"),
    GUJ("Gujarati"),
    GV("Manx"),
    GWI("Gwich?in"),
    HA("Hausa"),
    HAI("Haida"),
    HAT("Haitian; Haitian Creole"),
    HAU("Hausa"),
    HAW("Hawaiian"),
    HE("Hebrew", "heb"),
    HER("Herero"),
    HI("Hindi"),
    HIL("Hiligaynon"),
    HIM("Himachali"),
    HIN("Hindi"),
    HIT("Hittite"),
    HMN("Hmong"),
    HMO("Hiri Motu"),
    HO("Hiri Motu"),
    HR(false, false, "Croatian", "hrv"),
    HSB("Upper Sorbian"),
    HT("Haitian; Haitian Creole"),
    HU(false, true, "Hungarian", "hun", "hungarian"),
    HUP("Hupa"),
    HY(false, false, "Armenian", "hye", "arm", "armean?"),
    HZ("Herero"),
    IA("Interlingua (International Auxiliary Language Association),"),
    IBA("Iban"),
    IBO("Igbo"),
    ID("Indonesian"),
    IDO("Ido"),
    IE("Interlingue"),
    IG("Igbo"),
    III("Sichuan Yi"),
    IJO("Ijo"),
    IK("Inupiaq"),
    IKU("Inuktitut"),
    ILE("Interlingue"),
    ILO("Iloko"),
    INA("Interlingua (International Auxiliary Language Association),"),
    INC("Indic (Other),"),
    IND("Indonesian"),
    INE("Indo-European (Other),"),
    INH("Ingush"),
    IO("Ido"),
    IPK("Inupiaq"),
    IRA("Iranian (Other),"),
    IRO("Iroquoian languages"),
    IS(false, true, "Icelandic", "isl"),
    IT(false, true, "Italian", "ita", "italian"),
    IU("Inuktitut"),
    JA("Japanese", "jpn"),
    JBO("Lojban"),
    JPR("Judeo-Persian"),
    JRB("Judeo-Arabic"),
    JV("Javanese", "jav"),
    KA(false, false, "Georgian", "kat"),
    KAA("Kara-Kalpak"),
    KAB("Kabyle"),
    KAC("Kachin"),
    KAL("Kalaallisut; Greenlandic"),
    KAM("Kamba"),
    KAN("Kannada"),
    KAR("Karen"),
    KAS("Kashmiri"),
    KAU("Kanuri"),
    KAW("Kawi"),
    KAZ("Kazakh"),
    KBD("Kabardian"),
    KG("Kongo"),
    KHA("Khasi"),
    KHI("Khoisan (Other),"),
    KHM("Khmer"),
    KHO("Khotanese"),
    KI("Kikuyu; Gikuyu"),
    KIK("Kikuyu; Gikuyu"),
    KIN("Kinyarwanda"),
    KIR("Kirghiz"),
    KJ("Kuanyama; Kwanyama"),
    KK("Kazakh"),
    KL("Kalaallisut; Greenlandic", "kal"),
    KM("Khmer"),
    KMB("Kimbundu"),
    KN("Kannada"),
    KO("Korean"),
    KOK("Konkani"),
    KOM("Komi"),
    KON("Kongo"),
    KOR("Korean"),
    KOS("Kosraean"),
    KPE("Kpelle"),
    KR("Kanuri"),
    KRC("Karachay-Balkar"),
    KRO("Kru"),
    KRU("Kurukh"),
    KS("Kashmiri"),
    KU("Kurdish"),
    KUA("Kuanyama; Kwanyama"),
    KUM("Kumyk"),
    KUR("Kurdish"),
    KUT("Kutenai"),
    KV("Komi"),
    KW("Cornish"),
    KY("Kirghiz"),
    LA("Latin", "lat", "latin?"),
    LAD("Ladino"),
    LAH("Lahnda"),
    LAM("Lamba"),
    LAO("Lao"),
    LB("Letzeburgesch; Luxembourgish"),
    LEZ("Lezghian"),
    LG("Ganda"),
    LI("Limburgan; Limburger; Limburgish", "lim"),
    LIN("Lingala"),
    LN("Lingala"),
    LO("Lao"),
    LOL("Mongo"),
    LOZ("Lozi"),
    LT(false, true, "Lithuanian", "lit"),
    LTZ("Luxembourgish; Letzeburgesch"),
    LU("Luba-Katanga", "lub"),
    LUA("Luba-Lulua"),
    LUG("Ganda"),
    LUI("Luiseno"),
    LUN("Lunda"),
    LUO("Luo (Kenya and Tanzania),"),
    LUS("lushai"),
    LV(false, true, "Latvian", "lat"),
    MAD("Madurese"),
    MAG("Magahi"),
    MAH("Marshallese"),
    MAI("Maithili"),
    MAK("Makasar"),
    MAL("Malayalam"),
    MAN("Mandingo"),
    MAP("Austronesian (Other),"),
    MAR("Marathi"),
    MAS("Masai"),
    MDF("Moksha"),
    MDR("Mandar"),
    MEN("Mende"),
    MG("Malagasy"),
    MGA("Irish, Middle (900-1200),"),
    MH("Marshallese"),
    MI("Maori"),
    MIC("Mi'kmaq; Micmac"),
    MIN("Minangkabau"),
    MIS("Miscellaneous languages"),
    MK(false, false, "Macedonian", "mkd"),
    MKH("Mon-Khmer (Other),"),
    ML("Malayalam"),
    MLG("Malagasy"),
    MLT("Maltese"),
    MN("Mongolian"),
    MNC("Manchu"),
    MNI("Manipuri"),
    MNO("Manobo languages"),
    MO("Moldavian", "mol"),
    MOH("Mohawk"),
    MOL("Moldavian"),
    MOS("Mossi"),
    MR("Marathi"),
    MRI("Maori"),
    MS("Malay"),
    MSA("Malay"),
    MT(false, true, "Maltese"),
    MUL("Multiple languages"),
    MUN("Munda languages"),
    MUS("Creek"),
    MWL("Mirandese"),
    MWR("Marwari"),
    MY("Burmese"),
    MYA("Burmese"),
    MYN("Mayan languages"),
    MYV("Erzya"),
    NA("Nauru"),
    NAH("Nahuatl"),
    NAI("North American Indian"),
    NAP("Neapolitan"),
    NAU("Nauru"),
    NAV("Navajo; Navaho"),
    NB("Norwegian Bokmal; Bokmal", "nob"),
    NBL("Ndebele, South; South Ndebele"),
    ND("North Ndebele"),
    NDE("Ndebele, North; North Ndebele"),
    NDO("Ndonga"),
    NDS("Low German; Low Saxon; German, Low; Saxon, Low"),
    NE("Nepali"),
    NEP("Nepali"),
    NEW("Newari; Nepal Bhasa"),
    NG("Ndonga"),
    NIA("Nias"),
    NIC("Niger-Kordofanian (Other),"),
    NIU("Niuean"),
    NL(false, true, "Dutch; Flemish", "nld", "dut", "dutch"),
    NN("Norwegian Nynorsk; Nynorsk, Norwegian", "nno"),
    NO(false, true, "Norwegian", "nor", "norwegian"),
    NOG("Nogai"),
    NON("Norse, Old"),
    NR("South Ndebele"),
    NSO("Northern Sotho, Pedi; Sepedi"),
    NUB("Nubian languages"),
    NV("Navaho"),
    NWC("Classical Newari; Old Newari; Classical Nepal Bhasa"),
    NY("Nyanja; Chichewa; Chewa"),
    NYA("Chichewa; Chewa; Nyanja"),
    NYM("Nyamwezi"),
    NYN("Nyankole"),
    NYO("Nyoro"),
    NZI("Nzima"),
    OC("Occitan (post 1500),; Proven?al"),
    OCI("Occitan (post 1500),; Proven?al"),
    OJ("Ojibwa"),
    OJI("Ojibwa"),
    OM("Oromo"),
    OR("Oriya"),
    ORI("Oriya"),
    ORM("Oromo"),
    OS("Ossetian; Ossetic"),
    OSA("Osage"),
    OSS("Ossetian; Ossetic"),
    OTA("Turkish, Ottoman (1500-1928),"),
    OTO("Otomian languages"),
    PA("Panjabi; Punjabi"),
    PAA("Papuan (Other),"),
    PAG("Pangasinan"),
    PAL("Pahlavi"),
    PAM("Pampanga"),
    PAN("Panjabi; Punjabi"),
    PAP("Papiamento"),
    PAU("Palauan"),
    PEO("Persian, Old (ca.600-400 B.C.),"),
    PHI("Philippine (Other),"),
    PHN("Phoenician"),
    PI("Pali"),
    PL(false, true, "Polish", "pol"),
    PLI("Pali"),
    PON("Pohnpeian"),
    POR("Portuguese"),
    PRA("Prakrit languages"),
    PRO("Proven?al, Old (to 1500),"),
    PS("Pushto"),
    PT(false, true, "Portuguese", "por"),
    PUS("Pushto"),
    QU("Quechua", "que"),
    RAJ("Rajasthani"),
    RAP("Rapanui"),
    RAR("Rarotongan"),
    RM("Raeto-Romance"),
    RN("Rundi"),
    RO(false, true, "Romanian", "ron", "romanian"),
    ROA("Romance (Other),"),
    ROH("Raeto-Romance"),
    ROM("Romany"),
    RU(false, false, "Russian", "rus", "russian"),
    RUN("Rundi"),
    RW("Kinyarwanda"),
    SA("Sanskrit", "san"),
    SAD("Sandawe"),
    SAG("Sango"),
    SAH("Yakut"),
    SAI("South American Indian (Other),"),
    SAL("Salishan languages"),
    SAM("Samaritan Aramaic"),
    SAS("Sasak"),
    SAT("Santali"),
    SC("Sardinian", "srd"),
    SCN("Sicilian"),
    SCO("Scots"),
    SD("Sindhi"),
    SE("Northern Sami"),
    SEL("Selkup"),
    SEM("Semitic (Other),"),
    SG("Sango"),
    SGA("Irish, Old (to 900),"),
    SGN("Sign Languages"),
    SHN("Shan"),
    SI("Sinhala; Sinhalese"),
    SID("Sidamo"),
    SIN("Sinhala ; Sinhalese"),
    SIO("Siouan languages"),
    SIT("Sino-Tibetan (Other),"),
    SK(false, true, "Slovak", "slk"),
    SL(false, true, "Slovenian", "slv"),
    SLA("Slavic (Other)", "slavon?"),
    SM("Samoan", "smo"),
    SMA("Southern Sami"),
    SME("Northern Sami"),
    SMI("Sami languages (Other),"),
    SMJ("Lule Sami"),
    SMN("Inari Sami"),
    SMS("Skolt Sami"),
    SN("Shona"),
    SNA("Shona"),
    SND("Sindhi"),
    SNK("Soninke"),
    SO("Somali"),
    SOG("Sogdian"),
    SOM("Somali"),
    SON("Songhai"),
    SOT("Sotho, Southern"),
    SQ(false, false, "Albanian", "sqi", "albanian"),
    SR(false, false, "Serbian", "srp"),
    SRR("Serer"),
    SS("Swati"),
    SSA("Nilo-Saharan (Other),"),
    SSW("Swati"),
    ST("Sotho, Southern"),
    SU("Sundanese"),
    SUK("Sukuma"),
    SUN("Sundanese"),
    SUS("Susu"),
    SUX("Sumerian"),
    SV(false, true, "Swedish", "swe", "swedish"),
    SW("Swahili"),
    SWA("Swahili"),
    SYR("Syriac"),
    TA("Tamil", "tam"),
    TAH("Tahitian"),
    TAI("Tai (Other)"),
    TAT("Tatar"),
    TE("Telugu", "tel"),
    TEM("Timne"),
    TER("Tereno"),
    TET("Tetum"),
    TG("Tajik", "tgk"),
    TGL("Tagalog"),
    TH("Thai", "tha"),
    TI("Tigrinya", "tir"),
    TIG("Tigre"),
    TIV("Tiv"),
    TK("Turkmen", "tuk"),
    TKL("Tokelau"),
    TL("Tagalog"),
    TLH("Klingon; tlh I ngan-Hol"),
    TLI("Tlingit"),
    TMH("Tamashek"),
    TN("Tswana", "tsn"),
    TO("Tonga (Tonga Islands)", "ton"),
    TOG("Tonga (Nyasa),"),
    TPI("Tok Pisin"),
    TR(false, false, "Turkish", "tur", "turkish"),
    TS("Tsonga", "tso"),
    TSI("Tsimshian"),
    TT("Tatar"),
    TUM("Tumbuka"),
    TUP("Tupi languages"),
    TUT("Altaic (Other),"),
    TVL("Tuvalu"),
    TW("Twi", "twi"),
    TY("Tahitian"),
    TYV("Tuvinian"),
    UDM("Udmurt"),
    UG("Uyghur; Uighur", "uig"),
    UGA("Ugaritic"),
    UK(false, false, "Ukrainian", "ukr"),
    UMB("Umbundu"),
    UND("Undetermined"),
    UR("Urdu", "urd"),
    UZ("Uzbek", "uzb"),
    VAI("Vai"),
    VE("Venda", "ven"),
    VI("Vietnamese", "vie"),
    VO("Volap%9Fk", "vol"),
    VOT("Votic"),
    WA("Walloon"),
    WAK("Wakashan languages"),
    WAL("Walamo"),
    WAR("Waray"),
    WAS("Washo"),
    WEN("Sorbian languages"),
    WLN("Walloon"),
    WO("Wolof", "wol"),
    XAL("Kalmyk"),
    XH("Xhosa", "xho"),
    YAO("Yao"),
    YAP("Yapese"),
    YI("Yiddish", "yid"),
    YO("Yoruba", "yor"),
    YPK("Yupik languages"),
    ZA("Zhuang; Chuang", "zha"),
    ZAP("Zapotec"),
    ZEN("Zenaga"),
    ZH("Chinese", "zho"),
    ZND("Zande"),
    ZU("Zulu", "zul"),
    ZUN("Zuni");

    private boolean core;
    private boolean activeByDefault;
    private String name;
    private String[] alternatives;

    Language(boolean core, boolean activeByDefault, String name, String... alternatives) {
        this.core = core;
        this.activeByDefault = activeByDefault;
        this.name = name;
        this.alternatives = alternatives;
    }

    Language(boolean core, String name, String... alternatives) {
        this(core, false, name, alternatives);
    }

    Language(String name, String... alternatives) {
        this(false, name, alternatives);
    }

    public String getCode() {
        return toString().toLowerCase();
    }

    public String getName() {
        return name;
    }

    public String[] getAlternatives() {
        return alternatives;
    }

    public boolean isCore() {
        return core;
    }

    public boolean isActiveByDefault() {
        return activeByDefault;
    }

    public static Language findByCode(String code) {
        if (code == null) {
            return null;
        }
        Language language = Language.EN;
        try {
            language = valueOf(code.toUpperCase());
        } catch (IllegalArgumentException e) {
          // swallow the exception when language cannot be found.
        }
        return language;
    }

    public static Language findByName(String name) {
        if (name != null) {
            for (Language language : values()) {
                if (language.getName().equalsIgnoreCase(name)) {
                    return language;
                }
            }
        }
        return Language.EN;
    }

    public static Set<Language> coreSet() {
        Set<Language> set = EnumSet.noneOf(Language.class);
        for (Language language : Language.values()) {
            if (language.isCore()) {
                set.add(language);
            }
        }
        return set;
    }

    public static Set<Language> activeByDefaultSet() {
        Set<Language> set = EnumSet.noneOf(Language.class);
        for (Language language : Language.values()) {
            if (language.isActiveByDefault()) {
                set.add(language);
            }
        }
        return set;
    }

}
